version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      PORT: "8080"
      REDIS_ADDR: "redis:6379"
      KAFKA_ADDR: "broker:9093"
    ports:
      - "8080:8080"
    depends_on:
      - broker
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9094
      KAFKA_LISTENERS: PLAINTEXT://broker:9093,CONTROLLER://broker:9094,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"
      - "9093:9093"  # Internal port for communication between containers
      - "9094:9094"  # Internal port for controller