version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./logs:/app/logs
    environment:
      PORT: "8080"
      REDIS_ADDR: "redis:6379"
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]